#!/usr/bin/env node

const fs = require('fs')

const w = 80
const h = 9

const prefix = '```'
const suffix = '```'

const stars = '⟡⋄.·+*..⋆✧ ·˚·..⠁⠂⠐⠠⡀⢀⠁⠂⠐⠠⡀⢀*·.✺·*⊹⊹⊹.'.split('').concat([
  '✨',
])

const lines = []

const getStar = () => stars[Math.round(Math.random()*(stars.length-1))]
for (let y = 0; y < h; y++) {
  let line = ''
  for (let x = 0; x < w; x++) {
    line = line.concat(Math.random() < 0.08 ? getStar() : ' ')
  }
  lines.push(line)
}

let output = ''

for (let line of lines) {
  output = output.concat(line).concat('\n')
}

output = prefix + output + suffix

fs.writeFileSync('README.md', output)

console.log(output.replace(/&nbsp;/g, ' ').replace(/<br\/>/g, '\n'))
